# Generated by Django 5.2.7 on 2025-10-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
