# Generated by Django 5.2.5 on 2025-08-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thoikhoabieu',
            table='app_thoikhoabieu',
        ),
    ]
