# Generated by Django 5.2.5 on 2025-08-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
