# Generated by Django 5.2.5 on 2025-08-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
