# Generated by Django 5.2.5 on 2025-08-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeuser',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
