# Generated by Django 5.2.5 on 2025-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_typeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
